### ISSUE TITLE
Very odd crash that's been common among almost every version, StackOverflow

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#149]
The access and onComplete loop continue on and on.

https://fabric.io/aidan-follestads-projects/android/apps/com.afollestad.cabinet/issues/5523175a5141dcfd8f5d37b8

```Gradle
java.lang.StackOverflowError
       at android.os.Binder.(Binder.java:176)
       at android.app.IServiceConnection$Stub.(IServiceConnection.java:15)
       at android.app.LoadedApk$ServiceDispatcher$InnerConnection.(LoadedApk.java:967)
       at android.app.LoadedApk$ServiceDispatcher.(LoadedApk.java:984)
       at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:883)
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1650)
       at android.app.ContextImpl.bindService(ContextImpl.java:1633)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
       at android.media.MediaScannerConnection.connect(MediaScannerConnection.java:119)
       at android.media.MediaScannerConnection.scanFile(MediaScannerConnection.java:238)
       at com.afollestad.cabinet.file.LocalFileUtils.updateMediaDatabase()
       at com.afollestad.cabinet.file.LocalFileUtils.copyFile()
       at com.afollestad.cabinet.file.LocalFileUtils.access$100()
       at com.afollestad.cabinet.file.LocalFileUtils$7.onComplete()
       at com.afollestad.cabinet.file.LocalFileUtils.copyFile()
       at com.afollestad.cabinet.file.LocalFileUtils.access$100()
       at com.afollestad.cabinet.file.LocalFileUtils$7.onComplete()
       at com.afollestad.cabinet.file.LocalFileUtils.copyFile()
       at com.afollestad.cabinet.file.LocalFileUtils.access$100()
       at com.afollestad.cabinet.file.LocalFileUtils$7.onComplete()
       at com.afollestad.cabinet.file.LocalFileUtils.copyFile()
       at com.afollestad.cabinet.file.LocalFileUtils.access$100()
       at com.afollestad.cabinet.file.LocalFileUtils$7.onComplete()
       at com.afollestad.cabinet.file.LocalFileUtils.copyFile()
       at com.afollestad.cabinet.file.LocalFileUtils.access$100()
       at com.afollestad.cabinet.file.LocalFileUtils$7.onComplete()
       at com.afollestad.cabinet.file.LocalFileUtils.copyFile()
       at com.afollestad.cabinet.file.LocalFileUtils.access$100()
       at com.afollestad.cabinet.file.LocalFileUtils$7.onComplete()
       at com.afollestad.cabinet.file.LocalFileUtils.copyFile()
       at com.afollestad.cabinet.file.LocalFileUtils.access$100()
       at com.afollestad.cabinet.file.LocalFileUtils$7.onComplete()
```

**Comment by afollestad** [comment]
Looks like it's not only copying, based on user reports

![screen shot 2015-04-07 at 12 57 52 pm](https://cloud.githubusercontent.com/assets/1820165/7029802/bf838986-dd25-11e4-8423-041739120573.png)

**Comment by afollestad** [comment]
https://github.com/afollestad/cabinet/commit/d74329aae62912cc5ae51db402f4ae272ae00667 may or may not fix it, I can't be 100% sure because there's so many different user cases that caused this issue. I've never been able to reproduce it.

**Comment by afollestad** [comment]
Will re-open if it occurs again
