### ISSUE TITLE
Another very odd crash from Fabric.io (81 crashes from 23 users)

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#150]
Possibly an Xposed issue?

https://fabric.io/aidan-follestads-projects/android/apps/com.afollestad.cabinet/issues/5521d23a5141dcfd8f5ad027

```Gradle
android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:656)
       at android.view.LayoutInflater.inflate()
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.afollestad.cabinet.adapters.NavigationDrawerAdapter.onCreateViewHolder()
       at com.afollestad.cabinet.adapters.NavigationDrawerAdapter.onCreateViewHolder()
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder()
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition()
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition()
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next()
       at android.support.v7.widget.LinearLayoutManager.layoutChunk()
       at android.support.v7.widget.LinearLayoutManager.fill()
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren()
       at android.support.v7.widget.RecyclerView.dispatchLayout()
       at android.support.v7.widget.RecyclerView.onLayout()
```

**Comment by afollestad** [comment]
This was related to that selector issue
