### ISSUE TITLE
One more odd crash from Fabric.io that effects users, but the log isn't specific

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#151]
There's no specific line number, but it keeps coming back with every version, and it's effected 11 users with 1.9.2.6.

https://fabric.io/aidan-follestads-projects/android/apps/com.afollestad.cabinet/issues/552230445141dcfd8f5b577c

```Gradle
java.lang.NullPointerException
       at com.afollestad.cabinet.fragments.content.DirectoryFragment$7$2.run()
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5598)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by afollestad** [comment]
After digging deeper into Fabric's crash logs, into other threads that have logs not included in the one above:

![screen shot 2015-04-07 at 1 03 42 pm](https://cloud.githubusercontent.com/assets/1820165/7029932/97510f0a-dd26-11e4-85ff-620888a13042.png)

**Comment by afollestad** [comment]
Will re-open it if occurs again
