### ISSUE TITLE
crash when using "save to" on M

### ISSUE THREAD

**Issue by ahmedre** [afollestad/cabinet-issue-tracker#329]
application code that looks like this:

```java
Intent shareIntent = new Intent(Intent.ACTION_SEND);
shareIntent.setType("application/json");
shareIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
shareIntent.putExtra(Intent.EXTRA_STREAM, uri);
context.startActivity(Intent.createChooser(shareIntent, "Save"));
```

correctly shows Cabinet as one of the potential handlers of this, with "save to" - unfortunately, selecting that option, and then selecting ok (when you see the list of files) causes a crash, 100% reproducible:

```
11-29 18:19:13.296  2596  2596 E WindowManager: android.view.WindowLeaked: Activity com.afollestad.cabinet.ui.MainActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{dbd1316 V.E...... R......D 0,0-1367,448} that was originally added here
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.app.Dialog.show(Dialog.java:319)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at com.afollestad.materialdialogs.h.show(MaterialDialog.java:1313)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at com.afollestad.materialdialogs.n.e(MaterialDialog.java:1304)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at com.afollestad.cabinet.b.v.a(PickerCab.java:104)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at com.afollestad.a.a.a(MaterialCab.java:41)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.support.v7.widget.ek.a(Toolbar.java:180)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.support.v7.widget.m.onMenuItemSelected(ActionMenuView.java:761)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.view.View.performClick(View.java:5198)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.view.View$PerformClick.run(View.java:21147)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:739)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.os.Looper.loop(Looper.java:148)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-29 18:19:13.296  2596  2596 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-29 18:19:13.304  4325  7779 W WindowManager: Failed looking up window
11-29 18:19:13.304  4325  7779 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@7eb371b does not exist
11-29 18:19:13.304  4325  7779 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8733)
11-29 18:19:13.304  4325  7779 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8724)
11-29 18:19:13.304  4325  7779 W WindowManager: 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2697)
11-29 18:19:13.304  4325  7779 W WindowManager: 	at com.android.server.wm.Session.remove(Session.java:187)
11-29 18:19:13.304  4325  7779 W WindowManager: 	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:242)
11-29 18:19:13.304  4325  7779 W WindowManager: 	at com.android.server.wm.Session.onTransact(Session.java:130)
11-29 18:19:13.304  4325  7779 W WindowManager: 	at android.os.Binder.execTransact(Binder.java:453)
```

notes:
- this happens on Android M (on a Nexus 6p). 
- uri here is a ContentProvider uri, since that's the correct way to share files now (see [here](http://blog.danlew.net/2015/10/07/sharing-files-on-android-in-a-world-with-runtime-permissions/) for details).
- if the uri is a path to an external storage directory, Cabinet behaves properly.
- if Cabinet has never been run, selecting "send to" just shows a completely blank screen (since no permissions were granted yet since the app was just installed).

**Comment by afollestad** [comment]
Duplicate https://github.com/afollestad/cabinet-issue-tracker/issues/300
